export default async function Page() {
  return (
    <section>
      <h1 className="font-bold text-2xl mb-8 tracking-tighter">
        hello, I&apos;m seolyeong bae 👋
      </h1>

      <div className="prose prose-neutral dark:prose-invert">
        <p>
          This is my initial portfolio site. this site is generated by Next.js
          and TailwindCSS
        </p>
      </div>
    </section>
  );
}
